name: Build ISOs

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      upload_to_b2:
        description: 'Upload ISOs to Backblaze B2'
        type: boolean
        default: false
  workflow_call:

env:
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}-iso
  cancel-in-progress: true

jobs:
  build-iso:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        image_name:
          - cordierite
          - cordierite-deck
          - cordierite-nvidia
          - cordierite-nvidia-open
        major_version: [43]
    steps:

      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # v1.3.1

      - name: Checkout Repo
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          submodules: recursive

      - name: Set Image Tag
        id: generate-tag
        shell: bash
        run: |
          TAG="stable"

          if [[ "${{ github.ref_name }}" == "testing" ]]; then
              TAG="testing"
          fi

          echo "tag=${TAG}" >> $GITHUB_OUTPUT

      # Docker requires lowercase registry references
      - name: Lowercase Registry
        id: registry_case
        uses: ASzc/change-string-case-action@d0603cd0a7dd490be678164909f65c7737470a7f # v6
        with:
          string: ${{ env.IMAGE_REGISTRY }}

      - name: Setup Bazzite Repo
        id: setup-bazzite-repo
        shell: bash
        run: |
          curl -Lo ${{ github.workspace }}/bazzite.repo https://copr.fedorainfracloud.org/coprs/ublue-os/bazzite/repo/fedora-${{ matrix.major_version }}/bazzite-org-bazzite-fedora-${{ matrix.major_version }}.repo

      - name: Build ISOs
        uses: jasonn3/build-container-installer@c9ef3de33236e66781ec37bd0485e8009eaefe24 # v1.4.0
        id: build
        with:
          arch: x86_64
          image_name: ${{ matrix.image_name }}
          image_repo: ${{ steps.registry_case.outputs.lowercase }}
          variant: 'Kinoite'
          version: ${{ matrix.major_version }}
          image_tag: ${{ steps.generate-tag.outputs.tag }}
          secure_boot_key_url: '${{ github.server_url }}/${{ github.repository }}/raw/main/secure_boot.der'
          enrollment_password: 'universalblue'
          iso_name: ${{ matrix.image_name }}-${{ steps.generate-tag.outputs.tag }}-amd64.iso
          enable_cache_dnf: "false"
          enable_cache_skopeo: "false"
          extra_boot_params: ${{ steps.generate-extra-params.outputs.extra-boot-params }}
          additional_templates: '/github/workspace/installer/lorax_templates/remove_root_password_prompt.tmpl /github/workspace/installer/lorax_templates/set_default_user.tmpl'
          repos: '/github/workspace/bazzite.repo /etc/yum.repos.d/fedora.repo /etc/yum.repos.d/fedora-updates.repo'

      - name: Move ISOs to Upload Directory
        id: upload-directory
        shell: bash
        run: |
          ISO_UPLOAD_DIR=${{ github.workspace }}/upload
          mkdir ${ISO_UPLOAD_DIR}
          mv ${{ steps.build.outputs.iso_path }}/${{ steps.build.outputs.iso_name }} ${ISO_UPLOAD_DIR}
          mv ${{ steps.build.outputs.iso_path }}/${{ steps.build.outputs.iso_name }}-CHECKSUM ${ISO_UPLOAD_DIR}
          echo "iso-upload-dir=${ISO_UPLOAD_DIR}" >> $GITHUB_OUTPUT
          echo "iso-name=${{ steps.build.outputs.iso_name }}" >> $GITHUB_OUTPUT

      - name: Upload ISOs and Checksum to Job Artifacts
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
        with:
          name: ${{ matrix.image_name }}-${{ steps.generate-tag.outputs.tag }}
          path: ${{ steps.upload-directory.outputs.iso-upload-dir }}
          if-no-files-found: error
          retention-days: 7
          compression-level: 0
          overwrite: true

      - name: Upload ISO to Backblaze B2
        if: github.event_name == 'release' || inputs.upload_to_b2 == true
        uses: yamatt/backblaze-b2-upload-action@v7
        with:
          key_id: ${{ secrets.B2_KEY_ID }}
          application_key: ${{ secrets.B2_APPLICATION_KEY }}
          bucket_name: ${{ secrets.B2_BUCKET_NAME }}
          file_path: ${{ steps.upload-directory.outputs.iso-upload-dir }}/${{ steps.upload-directory.outputs.iso-name }}
          remote_path: releases/${{ steps.generate-tag.outputs.tag }}/${{ steps.upload-directory.outputs.iso-name }}

      - name: Upload Checksum to Backblaze B2
        if: github.event_name == 'release' || inputs.upload_to_b2 == true
        uses: yamatt/backblaze-b2-upload-action@v7
        with:
          key_id: ${{ secrets.B2_KEY_ID }}
          application_key: ${{ secrets.B2_APPLICATION_KEY }}
          bucket_name: ${{ secrets.B2_BUCKET_NAME }}
          file_path: ${{ steps.upload-directory.outputs.iso-upload-dir }}/${{ steps.upload-directory.outputs.iso-name }}-CHECKSUM
          remote_path: releases/${{ steps.generate-tag.outputs.tag }}/${{ steps.upload-directory.outputs.iso-name }}-CHECKSUM
